import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nunitoSans = localFont({
  src: [
    {
      path: './fonts/NunitoSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/NunitoSans-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/NunitoSans-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/NunitoSans-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
