import type {Metadata} from "next";
import {Inter, Nunito, Roboto} from "next/font/google";
import "./globals.css";
import AppBar from "@/components/appBar";

const inter = Nunito({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
          <body className={inter.className}>
            {children}
            <AppBar/>
          </body>
        </html>
    );
}
